### ISSUE TITLE
Enquêtes utilisateurs MCCO2 <=> tests utilisateurs quantis

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#102]
En attendant de voir comment on pourrait recruter des utilisateurs pour faire des tests qualis, est-ce qu'on ne mettrait pas en place une petit questionnaire depuis MCCO2 quanti ? 
Une mini-enquête utilisateur sous forme de pop-in avec genre 5 questions ?

Et je sais pas du tout si c'est possible mais on pourrait avoir 5 questions / enquête mais plusieurs questions posées aléatoirement ?

**Comment by Clem-mrtn** [comment]
Suite à ce qu'on s'est dit la semaine dernière, ça pourrait être intéressant d'avoir une petite enquête utilisateur sur chaque site MCCO2 ou encore NGC pour en savoir un peu + sur nos utilisateurs _(habitudes , niveau de connaissance, fréquence, etc.)_

On avait pensé à un type form donc j'ai réfléchis à des questions et j'ai créé un premier formulaire : https://9ovj4s5egaq.typeform.com/to/uzr4tXLu 
(Evidemment le plan freemium, fait que je ne peux pas vous partager la partie workspace, juste le lien du formulaire) 

**Les questions que je me pose :** 
- Très concrètement comment l'intégrer sur le site MCCO2 ? J'ai vu qu'il y avait plusieurs façons de l'embeded sur le site 
- Aujourd'hui on a 9 questions (après c'est payant) : est-ce que c'est pas trop long pour une mini enquête utilisateur ? 
Si oui, est-ce qu'on raccourcis en 5 questions et on fait différentes enquêtes qu'on fait apparaître aléatoirement (aucune idée comment) ?
- Si vous avez d'autres questions en têtes + prio on peut aussi en changer quelques unes

**Comment by Clem-mrtn** [comment]
**Les questions :** 

Vous êtes : 
-	Un particulier
-	Un professionnel 

Comment avez-vous connu notre site web ?
-	Moteur de recherche 
-	Sites Datagir 
-	Grâce à nos autres simulateur Datagir 
-	Sites Internet 
-	Réseaux sociaux 
-	Autres 
- 
Pour quelles raisons vous êtes-vous rendus sur notre site web ? 
-	Je cherchais à connaître l’impact carbone d’un objet 
-	Je cherchais à m’informer de façon générale sur l’environnement
-	Je cherchais du contenu pédagogique sur l’environnement 
-      Autres

Quel est votre degré d’engagement dans l’écologie ? : 
-	Très fort 
-	Fort 
-	Moyen
-	Faible 
-	L’écologie ne m’intéresse pas 

Pensez-vous être bien informé sur l’écologie ?
-	Oui 
-	Non

Par quel moyen vous sensibilisez-vous à l’écologie ?
-	Médias : articles de presses 
-	Réseaux sociaux 
-	Communication du gouvernement 
-	Autres 

Connaissez-vous notre simulateur Nos Gestes Climat ?
-	 Oui
-	Non

Seriez-vous intéresser de connaître l’empreinte que vous avez sur le climat et de faire votre bilan carbone individuel ? 
-	Oui 
-	Non 

A quelle fréquence allez vous sur notre site internet ? : 
- Très souvent
- Assez souvent
- Peu souvent
- Jamais 

Autres en tête : 
Avez-vous confiance dans les informations que vous trouvez sur ce site ? 
-	Oui 
-	Non

**Comment by Clem-mrtn** [comment]
Typeform n'est peut-être pas le format adéquate.
A challenger avec les solutions : 
- Hotjar : https://www.hotjar.com/
- Airtable 

=> Tenter de mettre en place l'enquête pour tester sur MCCO2 parmi ces solutions

**Comment by martinregner** [comment]
Je l'ai intégré sur [Airtable](https://airtable.com/shroHVp7DyXVn9YMf) pour voir ce que ça donne. Ca me parait bien !
(juste modifié quelques intitulés @Clem-mrtn ; à voir aussi si le choix unique / choix multiples te va)

N'hésitez pas à directement le modifier également 🔽 https://airtable.com/appdsewDZTOchqILN/tblmBi2IjnItwziQG/viwAJ7G5kMAdtwXGX?blocks=hide

**Comment by Clem-mrtn** [comment]
Up

**Comment by florianpanchout** [comment]
J'ai fait un essai ici : https://survey--mcc-v2.netlify.app/

Si vous avez des suggestions pour le wording, je suis preneur.

---

> Quel est votre degré d’engagement dans l’écologie ?

Je ne saurais pas quoi répondre moi même. Est ce qu'il ne faudrait pas caractériser les réponses pour aider les gens ? (j'ai essayé de l'écrire mais aucune idée de ce que représente ces différents niveaux)

**Comment by florianpanchout** [comment]
En regardant les première réponses du questionnaire, je me demande si la question "Seriez-vous intéressé.e de connaître votre empreinte carbone sur le climat ?" est posée de la bonne façon : qui va répondre non ? 

Est ce qu'il ne faudrait pas intégrer dans l'intitulé une notion de temporalité et de localisation ? (exemple : "Auriez-vous voulu pouvoir calculer votre empreinte carbone personnelle directement sur ce site ?")

**Comment by martinregner** [comment]
Je te rejoins. J'ai changé la question.
(les résultats de cette question seront donc à interpréter légèrement différemment à partir du 9/09)
