### ISSUE TITLE
Mieux afficher les unités 

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#127]
On a différentes unités sur le site : 
- kg CO2e / unité
- kg CO2e / kg
- kg CO2e / m2 / année
- kg CO2e / km
- kg CO2e / litre

Il faudrait mieux les représenter sur les pages catégories et équivalent.

Je propose de laisser tomber le "1" (exemple : "1 smartphone") sur les [pages catégories ](https://monconvertisseurco2.fr/categories/numerique), et d'afficher l'unité uniquement en bas ("Valeurs exprimées en kg CO2e émis par produit comprenant la fabrication, la distribution et l'usage"), et de généraliser ce principe aux autres pages (Donc afficher "Bière" et plus "1 litre de bière" [ici](https://monconvertisseurco2.fr/empreinte-carbone/boisson))

Se pose aussi la question du chauffage qui a deux unités (m2 et année). Surtout dans l'[affichage tuile](https://monconvertisseurco2.fr/co2e) qui est maintenant problématique (on affiche la valeur pour 1m2, ce qui donne l'impression que notre chauffage à l'année a l'impact d'un t-shirt...)

**Comment by florianpanchout** [comment]
J'ai fait un essai ici : https://unit-display--monconvertisseurco2.netlify.app/

**Comment by Clemog** [comment]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/55186402/189309093-642c7ddb-754d-42f9-b151-99aa3356fffc.png">
Peut-être éviter d'afficher les crochets ?

**Comment by florianpanchout** [comment]
> Peut-être éviter d'afficher les crochets ?

C'est corrigé

> J'ai eu du mal à trouver l'unité du coup (peut-être pas assez visible si c'est seulement en base de page

Sur la page catégorie ou la page équivalent ?

> Peut etre annexe à cette issue mais il serait intéressant de pouvoir rentrer la surface de son logement si on veut (même si c'est juste une question de proportionnalité)

Yes, on pourrait imaginer un simulateur comme [transport](https://monconvertisseurco2.fr/empreinte-carbone/transport) avec un choix "maison / appartement" et un slider de m2. Ça prendrait 1 journée à développer 

> Pour l'affichage du chauffage en tuiles, effectivement, pas évident. Actuellement, la tuile (même si je coche appartement ou maison) affiche par m2 (surface moyenne d'un appart en France : 63m2 / maison: 113m2) (cf https://github.com/datagir/nosgestesclimat/blob/2a15557b03b24fa226ba812c923270085aa22725/data/logement/chiffres%20parc%20logements%20fran%C3%A7ais.yaml#L17)

J'ai corrigé ici https://github.com/datagir/monconvertisseurco2/issues/105

**Comment by Clem-mrtn** [comment]
Cette issue me paraît bien avancée, les modifications me paraissent suffisantes à ce stade 
j'ai créé une nouvelle issue sur le chauffage #189 
Est-ce qu'on peut la fermer ?
