### ISSUE TITLE
Affichage usage numérique - Page catégorie

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#143]
Pour faire suite à la discussion que l'on a eu ce matin : 
- Refonte de la page "catégorie" actuelle pour tendre vers une page _"mes usages dans la catégorie numérique"_ et afficher de manière dynamique l'impact de chaque usage comparé aussi à la fabrication

- Quelques idées : 
 Graphique dynamique 
Des cases à cocher pour affiner son usage (wifi, 4G etc.) 

Les pages _"Equivalent_" permettront de rentrer davantage dans la personnalisation par item et surtout de mettre en avant des ordres de grandeurs, pour se comparer à d'autres éléments comme le transport, l'alimentation etc. via des infographies

**Comment by Clem-mrtn** [comment]
J'ai tenté d'expliciter en user stories les enjeux de la page catégorie pour contextualiser un peu les attentes qu'on s'est fixé 

- [ ] En tant qu’utilisateur je veux comprendre en arrivant sur la page catégorie du simulateur que les usages numériques ont un impact plus faibles que la construction des devices que j’utilise.

=> Est-ce une information que l'on souhaite afficher immédiatement sur la page pour les utilisateurs qui ont la flemme de paramétrer leurs usages ?
Un peu comme MIT, au premier coup d'œil je peux déjà hiérarchiser l'impact carbone des transports  

- [ ] En tant qu’utilisateur je veux pouvoir renseigner mes usages numériques dans une semaine type pour me rendre compte de mon impact carbone usage numérique et le comparer à d’autres critères comme la construction des éléments.
      - En tant qu’utilisateur je veux pouvoir personnaliser simplement ma consommation de mails, streaming, visios, audioconférence, navigation sur une semaine, en renseignant des "quantités" et en cochant quelques cases d’affinage comme les réseaux utilisés ou encore les appareils utilisés.
      - En tant qu’utilisateur je veux visualiser l’impact carbone de mon usage numérique sur une semaine **(rapporté à l'année?)** comparé directement /immédiatement, avec l’empreinte carbone de la construction des devices ou encore l’empreinte carbone des objets de la catégorie "numérique" (une sorte de dezoom)

**Comment by Clem-mrtn** [comment]
- iframe attendu pour le 28/10 
=> mise en ligne de la page catégorie fin de semaine prochaine, mais les pages seront cachées dans le menu (comme divers)

**Comment by florianpanchout** [comment]
[2 propositions de design](https://www.figma.com/proto/8cDevHNLXyq6K1At3gGZh9/Mon-Convertisseur-CO2?page-id=2046%3A5408&node-id=2046%3A5409&viewport=997%2C821%2C0.51&scaling=min-zoom).
