### ISSUE TITLE
Affichage usage numérique - Page équivalent 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#144]
Ajouter toutes les hypothèses du configurateur pour paramétrer sa simulation : 

**Email** 
- Avec ou sans PJ
- Taille de la PJ
- Durée de stockage 
- Destinataire 
- Temps d'écriture (pas convaincue..)
- Lieu d'envoie / lieu de réception 

**Streaming :** 
- Temps
- Qualité de la vidéo 
- Terminaux 
- Réseaux 4G / Wifi 

**Vidéoconférence :** 
- Temps 
- Qualité 
- Réseaux 4G /Wifi
- Terminaux 

Vous voyez d'autres paramètres ? 
(La requête web est-ce qu'on est pas vraiment sur un truc ultra de niche, d'autant que les paramètres à modifier sont vmt pas ouf ?)

**Comment by florianpanchout** [comment]
> La requête web est-ce qu'on est pas vraiment sur un truc ultra de niche

> Temps d'écriture (pas convaincue..)

Est ce que justement ça ne fait pas parti du message ? De montrer aux gens que l'impact du numérique c'est pas les data-center de Google mais leurs devices à eux ?

J'ai mis en ligne [une première version de l'interface](https://numerique--impactco2.netlify.app/empreinte-carbone/usagenumerique/streamingvideo). Seul le paramètre `Qualité` a un impact pour l'instant.

--- 

@clemog j'utilise [ce fichier](https://github.com/datagir/impactco2/blob/numerique/src/data/rules.json) pour l'instant, afin de pouvoir rajouter des paramètres à la main. Hésite pas à le modifier si tu veux pouvoir tester.

Je me dis qu'il serait peut être judicieux de grouper certains FE commun entre les équivalents (FE d'utilisation des différents devices, etc...), afin d'éviter d'avoir à tout recopier à chaque fois

**Comment by Clemog** [comment]
> Est ce que justement ça ne fait pas parti du message ? De montrer aux gens que l'impact du numérique c'est pas les data-center de Google mais leurs devices à eux ?

Je suis d'accord, pour moi, c'est quelque chose qu'on ne connait pas vraiment et pourtant on peut lire dans les conseils parfois "attention à pas vous tromper dans les recherches pour pas en faire trop"

**Comment by Clem-mrtn** [comment]
> Est ce que justement ça ne fait pas parti du message ? De montrer aux gens que l'impact du numérique c'est pas les data-center de Google mais leurs devices à eux ?

Yes yes je suis d'accord
C'était + un questionnement, "la requête web" étant un usage numérique moins familier pour certains usagers , donc pas forcément ce qui sera très recherché mais le mettre justement pour désamorcer ce type de message (*"attention à pas vous tromper dans les recherches pour pas en faire trop"*) très bien 👍

**Comment by Clemog** [comment]
Je note ça ici mais potentiellement à supprimer
Je crois qu'il y a une erreur dans la cellule J46 de l'onglet streaming

**Comment by florianpanchout** [comment]
Je pense qu'il faut mettre la durée de vie dans les paramètres oui (et mettre le même default à tous). Parce que la c'est assez problématique comme affichage :/

**Comment by Clem-mrtn** [comment]
Top, j'ai regardé un peu mais y a plusieurs trucs que je ne comprends pas trop quand je joue avec les paramètres : 
- Pourquoi est-ce qu'on a 2 fois la région ? C'est pour le pays où on reçoit et pays émetteur ? 
- En jouant avec les paramètres je suis surprise de voir que l'usage des terminaux est super élevé pour la Chine, et passe au dessus de la construction des devices ?

On est sur une représentation graphique assez complexe pour un utilisateur sensibilisé mais pas "expert"

**Comment by Clemog** [comment]
> Je pense qu'il faut mettre la durée de vie dans les paramètres oui (et mettre le même default à tous). Parce que la c'est assez problématique comme affichage :/

Je comprends pas pourquoi c'est problématique ?

C'est possible de variabiliser cette durée de vie mais ça complexifie le yaml : aujourd'hui une règle "durée de vie" par appareil pour tous les usages ; si on variabilise, une ègle "durée de vie" par appareil pour chacun des usages (si règle commune, alors modifier la durée de vie d'un appareil pour l'un des usages modifiera la durée de vie pour tous les usages). Je vais explorer le mécanisme "recalcul" de publicodes pour essayer de simplifier

**Comment by Clemog** [comment]
> Top, j'ai regardé un peu mais y a plusieurs trucs que je ne comprends pas trop quand je joue avec les paramètres :
> 
> * Pourquoi est-ce qu'on a 2 fois la région ? C'est pour le pays où on reçoit et pays émetteur ?
> * En jouant avec les paramètres je suis surprise de voir que l'usage des terminaux est super élevé pour la Chine, et passe au dessus de la construction des devices ? (ex : pour la TV)
> 
> On est sur une représentation graphique assez complexe pour un utilisateur sensibilisé mais pas "expert"

Pour l'instant c'est une branche de tests donc tous les paramètres de calculs sont dans l'interface et les titres ne sont pas toujours précis. C'est bien la région "émetteur" et "récepteur" ici

**Comment by florianpanchout** [comment]
> Je comprends pas pourquoi c'est problématique ?

Ça ne te semble pas être un problème de dire que regarder une série sur son ordi émet moins de CO2 que sur son smartphone ? Soit on contextualise beaucoup plus cette information (ce qui complexifie encore plus une notion déjà assez obscure), soit on met une durée de vie commune à l'ensemble des appareils que l'on peut faire (ou non) évoluer.

Et ça ne me choque pas d'avoir la même durée de vie par device pour tous les usages (vu que j'utilise effectivement le même device). En plus ici l'affichage ne concerne qu'un usage à la fois donc ce sera transparent pour l'utilisateur non ?

**Comment by Clemog** [comment]
> Ça ne te semble pas être un problème de dire que regarder une série sur son ordi émet moins de CO2 que sur son smartphone ? Soit on contextualise beaucoup plus cette information (ce qui complexifie encore plus une notion déjà assez obscure), soit on met une durée de vie commune à l'ensemble des appareils que l'on peut faire (ou non) évoluer.

Je ne suis pas contre, je comprends l'idée mais ça veut dire remettre en question l'étude. Et non, ça ne me semble pas problématique au vu des données d'entrée. Ça me parait logique si un ordinateur a une durée de vie plus longue que le streaming ait moins d'impact que sur un téléphone qu'on change tous les 2 ans. C'est aussi un message je pense

**Comment by florianpanchout** [comment]
> Ça me parait logique si un ordinateur a une durée de vie plus longue que le streaming ait moins d'impact que sur un téléphone qu'on change tous les 2 ans. 

Ça me parait logique aussi. Mais est ce que c'est compréhensible pour l'utilisateur ? Si je change smartphone par TV, je m'attends à ce que les autres hypothèses restent les mêmes. Ou à minima qu'elles soient explicites. Déjà que je trouve assez complexe de faire passer le message qu'une partie de la construction est intégrée à l'usage, si en plus cette part change de façon invisible selon le device, j'ai peur que l'on ai beaucoup d'erreurs de lecture

**Comment by Clem-mrtn** [comment]
> Tous les autres FE du site sont pour la France métropolitaine. Ce serais étrange de pouvoir le changer ici non ?

Je suis d'accord, c'est un sujet que je voudrais aborder au point de 16h, ça créé pas mal d'incompréhension la présence des autres régions _(USA, chine etc)_ encore plus avec la notion d'émetteur / récepteur... 
Jusqu'ici on a uniquement travaillé avec des données nationales et donc FE français, la gymnastique entre différents FE sur ce cas présent et assez complexe pour l'utilisateur je trouve (l'ex de la TV pour la chine juste au dessus, avec la différence de mix électrique...)

**Comment by Clemog** [comment]
La V1 du modèle Publicodes pour tous les usages est en ligne :)

**Comment by florianpanchout** [comment]
La suite est traitée via les issues #156 #157 #158 #159 #160 #161 #162
