### ISSUE TITLE
[Éducation] Établissement du périmètre de la v1

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#153]
En se basant sur [la fiche produit](https://pad.incubateur.net/fCVeR-K8SCu2V62es2VLEw) et les délais (v1 pour décembre) :

- [ ] Définir nos utilisateurs
- [ ] Définir le message général à leur faire passer
- [ ] Définir le ou les angles utilisés pour y parvenir

**Comment by Clemog** [comment]
Quelques éléments de réflexions sur ces 3 points:

- **Nos utilisateurs:** l'idée est de toucher dans un premier temps un **public jeune**. Ce premier quiz est l'occasion de fournir un support pour les enseignants, animateurs, intervenants en classe par exemple pour sensibiliser aux enjeux climat via les données de Impact CO2 (On peut imaginer plusieurs déclinaisons de quizz, pour tous niveaux !). Nous pouvons dire que nous avons 2 utilisateurs : **les jeunes de 10 à 16 ans (et pas seulement les "élèves"**, utilisateurs finaux, et les **formateurs** qui pourraient jouer le role d'intermédiaires.

- **Le message:** L'objectif est de sensibiliser de manière simple et ludique sur les ordres de grandeurs de l'impact climat de ses activités, de ses habitudes, de ses consommations.

- **Les angles pour y parvenir:** 
- Dans un premier temps, l'aspect "jeu" est important. L'idée est de poser successivement différentes questions simples sur le sujet CO2, de comparer différents éléments différents postes entre eux accompagné par des explications **concises**. 
- L'aspect "compétition" via un score semble intéressant tant que la compétition ne prend pas le dessus sur le message. On doit essayer de susciter l'envie de répondre via un message en début de test du type "7 personnes sur 10 répondent correctement à plus de la moitié des questions ! A ton tour !" plutôt qu'en fin de test, dont le message pourrait être déceptif "Vous avez 2 bonnes réponses quand tous les autres en ont 8".
- Donner la possibilité de personnaliser le test a son propre mode de vie pourrait être un vrai pllus pour embarquer l'utilisateur. A chaque question thématique générale, une question "Et toi, tu en es ou ?" qui pourrait donner lieu en fin de quiz à une première photo de comparaison de sa consommation à certains postes (pour ensuite rediriger vers NGC ?)

**Comment by florianpanchout** [comment]
Trop cool, c'est beaucoup plus clair ! (au moins pour moi)

Quelques retours : 

> L'objectif est de sensibiliser de manière simple et ludique sur les ordres de grandeurs de l'impact climat de ses activités, de ses habitudes, de ses consommations.

Est-ce qu'on veut sensibiliser sur "ses" activités ? Ou plus globalement sur les activités humaines ? Par exemple, est-ce qu'un enfant qui ne prend pas l'avion ne sera pas sensibilisé sur l'impact de ce dernier ?

> "7 personnes sur 10 répondent correctement à plus de la moitié des questions ! A ton tour !"

Aha t'as déjà travaillé avec des ados ? Tu leur mets un message comme ça ils font une attaque de panique avant même de commencer le quiz

**Comment by Clemog** [comment]
> Est-ce qu'on veut sensibiliser sur "ses" activités ? Ou plus globalement sur les activités humaines ? Par exemple, est-ce qu'un enfant qui ne prend pas l'avion ne sera pas sensibilisé sur l'impact de ce dernier ?

Je suis carrément d'accord ! 

> Aha t'as déjà travaillé avec des ados ? Tu leur mets un message comme ça ils font une attaque de panique avant même de commencer le quiz

Oups 😅😂 J'avoue qu'en relisant, je me dis que t'as envie de balancer l'ordi avant de commencer

**Comment by martinregner** [comment]
Top !

Comme discuté cette semaine, j'avais posé quelques idées également [ici](https://github.com/datagir/impactco2/issues/111).

Ce que j'avais bien aimé avec l'approche du groupe 10 de HETIC, c'est que le jeu ne prend pas trop le dessus.
Il faut vraiment s'assurer que les messages passent au mieux, et que les élèvent ne sont pas juste dans la compet d'avoir le + de point, comme tu le dis Clément.
Dans un premier temps on peut complètement sortir un quizz sans score, juste une correction qui apparaît mais sans sommer le nombre d'erreurs.
