### ISSUE TITLE
Affichage des emojis

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#156]
Pour l'instant on affiche les emojis natifs dans les selects (alors que ce sont les emojis Twitter pour le reste du site). 

De plus l'emoji "tablette" est le même que "smartphone"

**Comment by florianpanchout** [comment]
Le problème ne se pose maintenant que sur la page categorie. Il est impossible de mettre des images dans un select natif. 3 solutions : 

1. On trouve un autre type d'input. Soit un select maison (peu viable) soit autre chose mais j'ai du mal à voir ce qui serait adapté
2. On enlève l'emoji du slider
3. On garde les emojis natifs (donc différents du reste du site, et identique tablette / smartphone

Je vote pour 2

**Comment by Clem-mrtn** [comment]
**Suite sprint planning du 08.11** : 

- Ne pas afficher les emojis dans le slider 👍

**Comment by florianpanchout** [comment]
Done
