### ISSUE TITLE
Uniformiser les durée de vie par défaut

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#157]
Les durées de vie des appareils ne sont pas les mêmes entre Impact CO2 (basé sur [cette étude](https://cloud.datagir.com/index.php/s/zBfwMWg5Nf6FDcH)) et Publicodes (basé sur [cette étude](https://cloud.datagir.com/index.php/s/cNGjHSf2x3iMLgj).

Les FE d'émissions de construction ne sont pas les mêmes non plus.

**Comment by Clem-mrtn** [comment]
Validé ensemble que par cohérence des sources de données utilisées, si on prend les FE de l'étude de Pierre, on prend également la durée de vie de cette étude 👍
