### ISSUE TITLE
Les FE de construction des devices sont très éloignés entre les études

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#164]
Les FE d'émissions de Negaoctet sont très éloignés de ceux de [cette étude](https://librairie.ademe.fr/dechets-economie-circulaire/1189-modelisation-et-evaluation-des-impacts-environnementaux-de-produits-de-consommation-et-biens-d-equipement.html) (utilisé comme base pour Impact CO2) : 

### Laptop (+ 29%)
- Negaoctet : 173,769
- ADEME : 134,7

### Tablette (+ 118%)
- Negaoctet : 97,02
- ADEME : 44,5

### Smartphone (+ 215 %)
- Negaoctet : 82,73
- ADEME : 26,239

### Ordinateur fixe + écran (- 21%)
- Negaoctet : 330.225 (267,428 + 62,797)
- ADEME : 416,92

### TV (- 49%)
- Negaoctet : 177,000
- ADEME : 349,87

Negaoctet n'explique pas ses résultats et l'ADEME va donc les intégrer à la base impact avec un disclaimer. 

Pour autant certains chiffres semblent beaucoup plus proche de la réalité (smartphone) que le chiffre que l'on utilise actuellement. Le message pouvant changer radicalement entre ces deux chiffres, il faudra s'accorder dessus avant la sortie du simulateur

**Comment by Clem-mrtn** [comment]
=> A valider avec Julia qu'on conserve les facteurs d'émissions qu'on utilise déjà sur Impact CO2 (étude de Pierre) et non ceux de négaoctet

**Comment by Clemog** [comment]
Pour la tablette c'est plutôt 52 si on suit Impact CO2 non ? https://impactco2.fr/numerique/tabletteclassique

**Comment by florianpanchout** [comment]
Les FE d'Impact CO2 sont donnés hors phase d'usage :)

**Comment by Clemog** [comment]
Alors je comprends pas que l'usage soit aussi faible pour un smartphone vs une tablette par rapport à ce qu'on peut analyser via les données NO

**Comment by florianpanchout** [comment]
Ah oui c'est étrange. Les Excel de l'étude annoncent une consommation annuelle de 1,6705kWh pour un Smartphone et de 31kWh pour une tablette

**Comment by Clemog** [comment]
Est ce qu'on ne devrait pas reprendre les ces données pour recalculer les puissances en mode actif des appareil ? 

Puissance en mode actif = conso annuelle / (365 * profil d'utiilsation par jour)

**Comment by florianpanchout** [comment]
Logiquement oui. Mais ces chiffres me paraissent très hasardeux non ? Une tablette a une batterie 2 fois plus grosse qu'un smarphone, pas 15 fois. Je rate quelque chose ?

**Comment by Clemog** [comment]
C'est vrai j'ai du mal à comprendre

Dans l'excel NO, dans l'un des onglet, on a pour le smartphone:
Puissance = 29100/(profil utilisation*365) = 29,75W (sans source, avec 29100 idem pour un laptop)

Dans un autre onglet, on a :
Puissance = 15/profil d'utilisation avec la remarque : un smartphone consomme en moyenne 15kWh en le rechargeant une fois par jour (sans source, sachant que pour les autres devices la valeur de la puissance est entrée brute)

**Comment by florianpanchout** [comment]
Issue créée sur ce sujet #179
