### ISSUE TITLE
Page équivalent - désactiver le slider automatique 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#165]
Pour faciliter la lecture, désactiver le slider automatique et arriver automatiquement sur la slide **"Terminal utilisé"** 
On passera à un "slider manuel"

**Comment by Clem-mrtn** [comment]
Question : si on tombe automatiquement sur cette slide : 
![image](https://user-images.githubusercontent.com/76995768/200353085-87473f5f-fc66-427e-b6f0-586f8a5433d8.png)

Le chiffre de l'impact CO2 affiché en haut est basé sur quel terminal par défaut ?

**Comment by florianpanchout** [comment]
Done
