### ISSUE TITLE
Valeur de mon impact - tous les usages numériques à 0

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#169]
Sur la page catégorie, lorsque je positionne tous mes curseurs à 0 j'ai quand même un impact de 0,0005Kg de CO2e ce qui n'est pas très compréhensible 
![image](https://user-images.githubusercontent.com/76995768/200547382-915c7273-3f37-42ce-bcdb-ae6d03638970.png)
Je ne sais pas si c'est un bug ou si on prend d'autres paramètres en compte mais ce n'est pas très clair pour l'utilisateur de mettre tous ses usages à 0 et d'avoir quand même un (microscopique) impact
Il faudrait afficher 0 Kg de CO2

**Comment by florianpanchout** [comment]
Il semblerait que ce soit l'impact de la construction des data-centers (`streaming . data center . construction`). Mais il devrait être à zéro aussi. 

@Clemog

**Comment by florianpanchout** [comment]
L'impact de la construction des data-centers est fixe dans les configurateur de NegaOctet. 

C'est un peu étrange, il s'agit d'un prorata du nombre d'abonnés Netflix (167 millions, B37) par le temps moyen de visionnage quotidien (2h) ramené à l'année (B38).

En gros on attribue à chaque utilisateur du service la même part de la construction, peu importe ses usages.

**Comment by Clem-mrtn** [comment]
> En gros on attribue à chaque utilisateur du service la même part de la construction, peu importe ses usages.

Même si son usage c'est 0 donc ? 
Nous on peut "forcer" le 0, quitte à mettre un petit warning en expliquant qu'il y a toutefois un impact imputé à la construction des data center ?

**Comment by Clemog** [comment]
J'ajoute directement la condition d'applicabilité dans le modèle @florianpanchout : l'email devient "non applicable" si le poids est nul. Je crois la "non applicabillité" rend le score `undefined`

**Comment by florianpanchout** [comment]
Ça mets toutes les variables enfants à null aussi, ce qui est un peu embêtant (voir https://github.com/datagir/impactco2/issues/171#issuecomment-1308571058)

**Comment by Clemog** [comment]
Yes ! Je vais mettre une variation je pense du coup, à tester !

**Comment by Clemog** [comment]
C'est mieux @florianpanchout ?

**Comment by florianpanchout** [comment]
Yes, ça fonctionne maintenant :)
