### ISSUE TITLE
Nombres d'heures par an - Streaming & Visioconférence page catégorie

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#170]
Dans le graphique du bas on convertit le nombre de mails ou heures par semaine en année.
J'ai l'impression que pour les mails on multiplie par 52 semaines 
Ex : j'envoie 99 mails par semaine *(j'ai pas réussi à atteindre 100 avec le curseur 😅)*, j'ai la valeur **5148 mails** dans mon graph à l'année (99x52)

Par contre pour la visio ou le stream j'ai l'impression qu'on ne multiplie pas par le même nombre de semaines ?

**Comment by florianpanchout** [comment]
My bad. C'était le nombre de minute à la semaine qui était affiché... C'est corrigé
