### ISSUE TITLE
Afficher uniquement les appareils utilisés dans le graphique "Détails de mon impact" - page catégorie 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#171]
Suite à des retours utilisateurs, il est effectivement plus clair de n'afficher que **les appareils sélectionnés au dessus**, dans le graphique du détail de son impact à l'année
Quitte à proposer une option **"afficher la construction de tous les appareils"**

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
Sur le graphique du bas, si je renseigne 0 à l'un de mes usages il apparaît toujours dans le graphique du bas, ainsi que le device qui est sélectionné
**Vu que le graphique est *personnalisé* sur ce que l'on renseigne au dessus est-ce qu'on ne ferait pas apparaître les usages à 0, ainsi que les appareils ?** 

![image](https://user-images.githubusercontent.com/76995768/200811138-3d6aa01e-8d07-48e8-9617-84e2b82e1a86.png)
(sorry pour la petite taille...) 
Ici lorsque mes mails sont à 0, avec un smartphone, j'ai dans le graphique l'usage des mails + la construction du smartphone alors que l'appareil n'est pas utilisé ailleurs

**Comment by florianpanchout** [comment]
Lié à https://github.com/datagir/impactco2/issues/169#issuecomment-1308759892

**Comment by florianpanchout** [comment]
C'est bon sinon pour l'affichage conditionnel des usages et appareils
