### ISSUE TITLE
Page catégorie - réintégrer le graphique impact de ses usages à la semaine 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#172]
Comme je le mentionnais dans l'issue #166, suite à des retours utilisateurs et parce qu'on accompagne mieux sa réflexion, je trouverais ça pertinent de réintégrer le graphique qui découpe les usages à la semaine 
Ca répond à plusieurs questionnements : 
- Je retrouve plus clairement le découpage de mon impact 
- je visualise clairement que le device utilisé n'a pas d'impact dans mon usage (voir issue #173) : j'ai eu le retour que lorsque l'on donne uniquement la valeur total de l'impact et non découpé, on peut penser que le device joue un tout petit rôle dans le poids de l'impact (genre 0,0001 kg) mais que comme on arrondi l'impact total cela ne s'affiche pas. Avec le graph et le découpage on se rend compte que ça n'a pas d'impact.

**Comment by florianpanchout** [comment]
Je pense qu'il y a un problème dans les données pour l'impact de l'usage du device. @Clemog erreur lors du changement du mix énergétique ?

**Comment by florianpanchout** [comment]
Pas fan de l'idée de réintégrer le graph. Il met trop en avant la comparaison relative des usages entre eux (ce qui peut laisser à penser que certains ont un impact très important). On a au final la même information en dessous mais mise en perspective avec la construction

**Comment by Clem-mrtn** [comment]
Je ferme l'issue du coup
