### ISSUE TITLE
[iframe] CTA sous les catégories

### ISSUE THREAD

**Issue by martinregner** [datagir/impactco2#174]
Sur Transport le CTA est "Voir toutes les catégories" et renvoie vers l'accueil (nouvelle fenêtre).
Tous les autres secteurs ont "Comparer les catégories" qui n'est pas encore codé.

Je propose de mettre partout le même CTA que sur Transport

**Comment by Clem-mrtn** [comment]
Que ce soit sur l'iframe ou sur le site d'ailleurs 
On pourrait changer le CTA de toutes les pages catégories (iframe & page du site) par **"Voir toutes les catégories"**

**Comment by florianpanchout** [comment]
Done. On a maintenant tout le temps "Voir toutes les catégories" qui renvoie vers l'accueil
