### ISSUE TITLE
Même valeur pour l'email entre les pages catégories et équivalent 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#176]
Homogénéiser les hypothèse et les valeurs pour un mail entre les pages Catégorie usages numériques et Equivalent pour éviter la confusion et une différence de résultats entre les deux pages 
=> prendre par exemple 300 Ko pour un mail sans pj

**Comment by florianpanchout** [comment]
Est ce que cette issue a encore du sens maintenant que l'on laisse le choix du poids de l'email sur la page catégorie ? La valeur de la page équivalent correspond à l'option "Pièce jointe 1Mo", ça me semble cohérent

**Comment by Clemog** [comment]
Je partage, même si 1 Mo pour un mail avec pièce jointe me parait élevé ? Et du coup dans la page équivalent, pas évident de jouer avec le slider de la taille non ?

**Comment by Clem-mrtn** [comment]
Yes ça me va on retrouve maintenant les même résultats de la page catégorie à la page équivalent 👍 
Est-ce qu'on explique les hypothèses dans une petite modale ou en bas de page sur la page catégorie ?

**Comment by Clem-mrtn** [comment]
>Je partage, même si 1 Mo pour un mail avec pièce jointe me parait élevé ?

Je m'amusais à regardais un peu mes docs, ça dépend tellement des fichiers : pour les words & les excels on est sur une centaine de Ko, pour les PPT direct c'est genre 8/10 Mo... 
Du coup bon ça me parait être une bonne moyenne quand meme 1 et 5 Mo

> Et du coup dans la page équivalent, pas évident de jouer avec le slider de la taille non ?

Quel slider ? Le slider de la pièce jointe ?

**Comment by florianpanchout** [comment]
C'est vrai. J'ai changé le label pour "Poids de l'email" et mis des pas de 0.1Mo plutôt que 1Mo
