### ISSUE TITLE
🐛 Précédent page équivalent

### ISSUE THREAD

**Issue by Clemog** [datagir/impactco2#177]
Je remonte un bug du comportement du bouton "précédent" du navigateur sur les pages équivalent :

**Cas d'usage :**
Je suis sur la page catégorie Numérique, je clique sur Smartphone, je visualise les slides d'infographies (j'ajoute un URL param). Quand je clique sur précédent, je reviens donc à l'url d'avant et donc sur la slide d'avant sur la même page équivalent alors que je m'attends à retourner sur la page catégorie

**Comment by florianpanchout** [comment]
Yes, c'est vrai que l'on devrait changer le hash et pas le query (ça fout aussi le bordel sur le tracking Matomo)

**Comment by Clem-mrtn** [comment]
On a pas le problème avec le slider sur la [page équivalent d'un usage numérique](https://impactco2.fr/usagenumerique/email) : je peux faire défiler les slides et quand je clique sur précédent je retombe bien sur la page catégorie. 
Effectivement l'URL ne change pas (on n' pas slide1, slide 2, slide 3..) : ce serait pas possible de le paramétrer pareil sur les autres pages équivalent ?
