### ISSUE TITLE
Modifier le FE du smartphone

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#178]
Pour l'instant, on prends le FE du smartphone de 5 pouces. L'étude propose aussi le FE d'émission du smartphone > 5.5 pouces. 
On passerait de 26 kg CO2e à 31 kg CO2e en changeant

Dans tous les cas, je pense qu'on est bien dessous de la réalité : 
- [Impact de l'iPhone SE (4,7 pouces)](https://www.apple.com/environment/pdf/products/iphone/iPhone_SE_PER_March2022.pdf)
- [Impact de l'iPhone 14 Pro (6,1 pouces)](https://www.apple.com/environment/pdf/products/iphone/iPhone_14_Pro_PER_Sept2022.pdf)

**Comment by florianpanchout** [comment]
@Clem-mrtn @Clemog @martinregner

**Comment by Clemog** [comment]
La remarque d'un test utilisateur ce matin avec les nouvelles données :

"Ah ok le streaming, c'est comme le smartphone" :/

**Comment by florianpanchout** [comment]
Bah en vrai, un peu non ? Si tu fais 2h30 de streaming par jour en 4K sur ta TV, niveau climat c'est comme si tu achetais chaque année un nouvel iPhone 14 Pro.

**Comment by Clem-mrtn** [comment]
Du coup, pour le smartphone tu suggères qu'on prenne plutôt l'étude NO que les FE de l'étude de Pierre ? 
Mais du coup, par rapport à l'issue #164, pour les restes des appareils on resterait sur les FE de l'étude de Pierre ?

**Comment by florianpanchout** [comment]
Non, les deux FE (`5 pouces` et `> 5,5 pouces`) viennent de l'étude de Pierre

**Comment by florianpanchout** [comment]
Done
