### ISSUE TITLE
Mettre à jour la description du smartphone 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#180]
La relou du détail le retour 😬 On prend maintenant le FE d'un smartphone>5,5 pouces 
le FE s'est bien actualisé sur les pages catégorie numérique, et équivalent smartphone mais il faudrait mettre à jour la description de l'objet sur la page équivalent : https://impactco2.fr/numerique/smartphone?slide=1

**Comment by florianpanchout** [comment]
Oups. C'est corrigé
