### ISSUE TITLE
Bug sélecteurs - impossible de revenir à un choix

### ISSUE THREAD

**Issue by martinregner** [datagir/impactco2#181]
Pour chaque écran (mail, streaming, visio), lorsque l'on a changé l'un des sélecteurs (Wifi/4G, SD/HD/4k ...) il n'est plus possible de revenir sur le choix précédent. Il n'est plus cliquable.

**Comment by florianpanchout** [comment]
Corrigé

**Comment by martinregner** [comment]
Le bug persiste pour :
- streaming, pour "Qualité de la vidéo"
- visio, pour "Qualité de la communication"

**Comment by florianpanchout** [comment]
Oups, j'ai lu trop vite ! Ça devrait être bon maintenant
