### ISSUE TITLE
Intégrer les textes courts sur les pages catégories

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#188]
Suite à la priorisation & la rédaction des textes pour le SEO #112, intégrer sur chaque page catégorie les textes courts rédigés par John 
*(une fois validé avec John cet a-m je te remets les textes directement sous l'issue pour y voir + clair)*

**Comment by Clem-mrtn** [comment]
**Catégorie Alimentation** 
Quel est l’impact climat d'un repas ? 

Le quart des émissions de gaz à effet de serre en France provient de nos assiettes, c’est autant que le logement ou le transport ! Un repas végétarien ou végétalien (0,5 et 0,4 kgCO2e) a beacoup moins d'impact pour la planète qu’un repas avec du bœuf ou du poulet (7 kgCo2e et 1,6 kgCO2e) ou encore avec du poisson (gras 1,1 kgCO2e et blanc 2 kgCO2e). Il est donc préférable de manger des produits d'origine végétale pour protéger l’écosystème de la planète.

**Catégorie Numérique** : 
Quel est l’impact sur le climat du numérique dans votre quotidien ?


L’empreinte carbone du secteur du numérique représente aujourd’hui 3 à 4% des émissions de gaz à effet de serre dans le monde et 2% de l’empreinte carbone à l’échelle nationale.
La grande majorité de l'impact du numérique provient de la fabrication des smartphones, ordinateurs, et tous les dispositifs que nous achetons. Pour limiter l'impact du numérique, il est donc primordial de garder le plus longtemps possible nos équipements et de privilégier les appareils reconditionnés : tous les métaux et matériaux utilisés pour la fabrication repartent ainsi pour une nouvelle vie.

**Catégorie mobilier** : 
Quel est l'impact du mobilier sur le climat ?

L'impact carbone d'un meuble comprenant la fabrication, la distribution et l’usage, peut aller de 19kg d’émissions de CO2 avec la chaise en bois, jusqu’à 907kg d’émissions de CO2 avec l’armoire. 

**Catégorie habillement** : 
Quel est l’impact sur le climat d'un vêtement ?

L’impact carbone d’ un habit comprenant la fabrication, la distribution et l’usage, peut aller de 6kg d’émissions de CO2 pour un t-shirt en polyester, jusqu’à 99kg d’émissions de CO2 pour un manteau.

**Catégorie transport** : 
Quel est l’impact sur le climat du secteur du transport ?

Avec 30%des émissions de CO2, le secteur des transports est le 1er secteur émetteur de gaz à effet de serre.
L’impact carbone d'un déplacement d'une distance de 10km peut aller de 0kg d’émission de CO2 avec la marche ou le vélo, jusqu’à 2,2kg d’émissions de CO2 avec une voiture thermique.

**Catégorie électroménager** : 
Quel est l’impact carbone du secteur de l’électroménager ? 

L’impact carbone du secteur de l’électroménager comprenant la fabrication, la distribution et l’usage, peut aller de 41kg d’émissions de CO2 avec une bouilloire, jusqu’à 513kg d’émissions de CO2 avec le lave-linge. 

**Catégorie chauffage** 
Quel est l’impact sur le climat du chauffage d'un logement ?


Que ce soit pour une maison ou un appartement, l’impact carbone du chauffage domestique par m2 et par année, peut aller de 3,7kg d’émissions de CO2 avec le chauffage électrique, jusqu’à 53kg d’émissions de CO2 avec le chauffage au fioul.

**Catégorie boisson** : 
Quel est l’impact sur le climat des boissons ?

L’impact carbone des boissons peut aller de 0,0001kg d’émissions de CO2 avec l’eau du robinet, comprenant l'impact de toute la gestion du réseau d'eau potable, jusqu’à 1,5kg d’émissions de CO2 avec le lait de vache. Pour les boissons embouteillées, les valeurs affichées comprennent l'impact de leur fabrication, de l'emballage, du transport, de toute la chaîne distribution y compris les supermarchés.

**Catégorie Usages numériques** 
Quel est l’impact sur le climat des usages numériques du quotidien ?

L’empreinte carbone du secteur du numérique représente aujourd’hui 3 à 4% des émissions de gaz à effet de serre dans le monde et 2% de l’empreinte carbone à l’échelle nationale.
La grande majorité de l'impact du numérique provient de la fabrication des smartphones, ordinateurs, et tous les dispositifs que nous achetons. L'impact carbone des mails va grandement varié selon la taille des pièces jointes et le nombre de destinataires, quand l'impact du streaming ou d'une visioconférence va varier selon la qualité de l'image. Enfin, la vidéo via 4G peut être jusqu'à 2 fois plus émétrice qu'avec une connexion Wifi.

**Comment by florianpanchout** [comment]
J'émets quelques doutes sur l'efficacité de notre méthode actuelle (rédaction côté SEO, relecture côté métier). J'ai l'impression qu'avoir une première version écrit côté produit serait plus efficace (on sait déjà de quoi on parle et ce que l'on essaie de montrer). Suivi par une double relecture com ADEME (pour améliorer le style littéraire) et SEO (pour améliorer la présence des mots clés).

J'ai écris [ce texte par exemple sur la page usage numérique](https://188--impactco2.netlify.app/usagenumerique) en assez peu de temps au final (30 minutes). C'est un brouillon qui mérite évidemment d'être améliorer mais ça montre ce qu'il est possible de faire avec cette méthode

**Comment by florianpanchout** [comment]
@Clemog J'ai intégré un composant `Learning` dans `Category`. Dans un premier temps il suffit juste de créer des nouveaux objets jsx avec le nom du slug de la category et de les ajouter au return en dessous.

@Clem-mrtn @martinregner J'ai l'impression que l'on s'est plus ou moins mis d'accord pour [cette nouvelle méthode de travail](https://github.com/datagir/impactco2/issues/188#issuecomment-1326199443) au séminaire. Comment on continue pour la suite ? Je contacte Florence et John directement pour leur demander de relire [le texte usage numérique](https://188--impactco2.netlify.app/usagenumerique) ?

**Comment by Clem-mrtn** [comment]
J'ai commencé à refaire une passe sur ton texte numérique, je continue de regarder ça et je te fais un retour. 
Pour la validation "métier" et pour une question d'efficacité je ne te cache pas que je préférerais que ce soit @martinregner qui valide (plutôt que Florence) et après ok pour validation SEO par John 👍

**Comment by Clemog** [comment]
Les textes sont en ligne sur la branche de démo: https://188--impactco2.netlify.app/
- Ajout des textes courts
- Remplacent parfois des textes plus longs qui étaient en ligne pour harmoniser

Point d'attention:
- Certains textes sont très courts et l'apparence est peut être un peu légère parfois
- Pour les F&L le contenu est différent car pas de texte court validé et c'éétait pourtant à changer car copier /coller si j'ai bien ciompris ?

**Comment by Clem-mrtn** [comment]
>Pour les F&L le contenu est différent car pas de texte court validé et c'éétait pourtant à changer car copier /coller si j'ai bien ciompris ?

En effet, @jondu33 aujourd'hui de ce que j'avais compris le copier-coller faisait que Google ne remontait pas bien le site ? Hors là on est sur un copier-coller du texte de [Mes fruits & légumes de saison](https://mesfruitsetlegumesdesaison.fr/)
Tu confirmes ? 

@Clemog pour le "texte court" de cette catégorie je pensais aussi qu'on avait produit un autre texte court. Je propose quelque chose

**Comment by Clem-mrtn** [comment]
Proposition : 
> **Quel est l’impact climat des fruits et légumes ?** 
Aujourd’hui 75% de Français déclarent consommer des tomates en hiver. Or une tomate produite hors saison a une empreinte carbone bien plus élevée puisqu'elle génère **4 fois plus de Kg de CO2e** que la même tomate produite à la bonne saison.
Afin de limiter ces émissions de gaz à effet de serre responsable du changement climatique, il est donc important de consommer les fruits & légumes du mois. 

Manger au moins 5 fruits et légumes par jour c’est bien, mais s’ils sont de saison c’est encore mieux pour la planète et pour vos papilles !

**Comment by florianpanchout** [comment]
> Pour les F&L le contenu est différent car pas de texte court validé et c'éétait pourtant à changer car copier /coller si j'ai bien ciompris ?


Nope il n'y a plus de problème maintenant. MFLDS référence Impact CO2 comme le contenu original, donc pas de sanction côté moteur de recherche

**Comment by Clem-mrtn** [comment]
> Les textes sont en ligne sur la branche de démo: https://188--impactco2.netlify.app/

C'est bon pour moi avec la correction de ces 2 petits points : 
- Sur le texte de l['impact des boissons](https://188--impactco2.netlify.app/boisson), rajouter "de toute la chaîne **de** distribution y compris..." 
- [Titre de la page électroménager](https://188--impactco2.netlify.app/electromenager), légèrement différent des autres => à harmoniser " **Quel est l'impact sur le climat d'un appareil électroménager ?**"

**Comment by florianpanchout** [comment]
> pour la validation "métier" et pour une question d'efficacité je ne te cache pas que je préférerais que ce soit @martinregner qui valide (plutôt que Florence)

Est-ce que tu essaies de te venger parce qu'il t'a refilé Wattris ? :p 

On a tout un service dont c'est le métier et qui souhaite plus collaborer avec nous. Selon moi ça ne coute rien d'essayer de passer par eux, et de réévaluer par la suite si ça ne fonctionne pas

**Comment by florianpanchout** [comment]
C'est en prod :)

(Je me suis permis de remettre une largeur maximal sur le texte de description des catégories)
