### ISSUE TITLE
Catégorie électroménager : afficher le détail des données pour l'impact du four 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#190]
Un adémien nous a fait un retour sur l'affichage de l'impact du four : https://impactco2.fr/electromenager
En effet nous n'avons pas le détail des données pour le four, tout son impact est donc imputé à la construction sur le graphique de la page catégorie et nous n'avons rien sur la page équivalent 
Il faudrait pouvoir rajouter les données suivantes de la Base Impact pour afficher le détail de l'impact 
![image](https://user-images.githubusercontent.com/76995768/201966759-27838c48-cdf6-4748-bf69-c69a11b20868.png)

Il semble aussi que le résultat selon l'étude ci-dessus soit plutôt **212Kg CO2e**

**Comment by florianpanchout** [comment]
Done (et merged)
