### ISSUE TITLE
Impact de la construction peu visible

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#192]
Le simulateur est souvent partagé sous forme de capture d'écran ([exemple](https://mobile.twitter.com/babgi/status/1593241145353510912)) qui coupe systématiquement l'impact de la construction.

Il semble important d'afficher dans cet espace l'impact de la construction, afin d'éviter les retours de gens qui ne se basent que sur la capture d'écran.

De plus, au vu des retours, il n'est pas évident de comprendre ce que l'on entends par l'impact de l'usage (juste usage des appareils ? Stockage de la donnée ? Construction des data-centers ?).

Je propose ce nouveau layout pour expliciter l'information affichée : 

![Image](https://user-images.githubusercontent.com/8115933/202702313-014da267-73c6-4612-878c-c64867357f82.png)

Ainsi on se couvrirait d'une certaine façon avec ce disclaimer forcement intégré au screenshot, et on pourrait en plus espérer que les gens ne coupent pas la phrase du bas "Par comparaison, la construction de vos appareils (smartphone, télévision et ordinateur portable) a émis 516 kg CO2e"

**Comment by florianpanchout** [comment]
@Clem-mrtn @martinregner

**Comment by Clem-mrtn** [comment]
Ca me va ! 👍 
Je me pose juste la question du placement du texte qu'on place juste en dessous "l'impact semaine" hors ces hypothèses sont aussi prises en compte pour "l'impact année" et les équivalents. 
Pourquoi ne pas mettre le texte juste en dessous des équivalents ? " Ces valeurs comprennent..." 

> Le simulateur est souvent partagé 

Pour info quand même, je fais pas mal le retour des réseaux depuis hier et les screenshot partagés prennent l'ensemble  du graphique hein

**Comment by Clem-mrtn** [comment]
Tu l'as mis dans TO DO donc c'est une issue rapide à traiter qu'on intègre dans le sprint en cours ?

**Comment by florianpanchout** [comment]
> Pourquoi ne pas mettre le texte juste en dessous des équivalents ? " Ces valeurs comprennent..."

Parce que si la personne fait une capture d'écran elle risque d'omettre cette partie

> Tu l'as mis dans TO DO donc c'est une issue rapide à traiter qu'on intègre dans le sprint en cours ?

Pas fait exprès aha. Je ne sais pas, j'ai l'impression que c'est un gros problème qui peut se régler facilement. Mais je base mon avis sur les 3 tweets que j'ai vu. Vous avez une meilleure vue d'ensemble que moi et donc une meilleure idée de la priorité à donner à cette issue

**Comment by florianpanchout** [comment]
Bon, j'étais lancé, j'ai fait un truc

**Comment by florianpanchout** [comment]
C'est corrigé !
