### ISSUE TITLE
Expliciter les sources et calculs 

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#193]
On ne cite aucune source, et on n'explicite aucun calcul sur le simulateur. Je vois 2 opportunité d'amélioration : 

- Texte explicatif sur la page catégorie, on l'on donnerait nos sources (je ne sais pas quoi mettre en dehors du lien vers le modèle Publicodes) et nos hypothèses non affichée.
- Lien "source" sur les pages équivalent. Je ne sais pas quoi mettre pour l'instant. Lien vers le modèle Publicodes ?

**Comment by Clem-mrtn** [comment]
Carrément j'allais faire une issue sur le sujet, on source très peu c'est un peu problématique
Ce serait bien qu'on cite aussi l'étude NO et peut-être l'étude de Pierre ?  

> peut-être l'étude de Pierre 

D'ailleurs à ce sujet, sans trop de surprise les résultats de l'étude est challengé dans des retours utilisateurs notamment sur les FE des smartphones et le fait qu'elle date de 2019.

**Comment by florianpanchout** [comment]
> Ce serait bien qu'on cite aussi l'étude NO

Je ne sais pas trop comment citer cette étude justement. Je pense qu'il vaut mieux assumer que notre source pour les usages c'est le modèle Publicodes (@Clemog est-ce qu'il existe un explorateur de ce modèle ou il faut directement linker le yaml ?)

Et ensuite c'est dans le modèle Publicodes que l'on retrouverait le détail des sources (qui existe déjà grâce au travail de @Clemog)

Est-ce que cette hiérarchisation vous semble cohérente ? Sachant qu'à terme, on pourrait l'appliquer à l'ensemble du site (Impact CO2 ne serait qu'une visualisation du/des modèles Publicodes et tout le travail de sourcing se ferait à ce niveau)

**Comment by florianpanchout** [comment]
Une première version d'à quoi pourrait ressembler le texte sur la page catégorie : 

> Les hypothèses suivantes sont utilisées pour cette page :

> Pour l'email :
On considère un temps de rédaction de 3 minutes, et un seul destinataire par email qui lirait le message en 10 secondes sur un appareil et un réseau équivalent à celui de l'expéditeur. L'email est considéré stocké pendant 10 ans côté expéditeur et destinataire. Un poids de 75ko a été retenu pour un email sans pièce-jointe. L'ensemble de l'impact (expéditeur et destinataire) est attribué à l'expéditeur. 
[Plus de détail et les sources des facteurs d'émissions sont disponibles ici](https://github.com/datagir/nosgestesclimat/blob/donn%C3%A9es-num%C3%A9rique/data/num%C3%A9rique/negaoctet/email%3E.yaml)

Est-ce que le format vous semble cohérent ? 

Il faudrait faire aussi la visio (pas grand chose à dire à part qu'on n'impute l'impact que d'un seul des participants) et le streaming (rien de spécifique à dire)

(@Clemog si tu peux vérifier que je ne dise pas de connerie...)

**Comment by Clemog** [comment]
Pour le message "hypothèse", ça me va ! Il pourrait être variabilisé avec les valeur par défaut aussi je pense non ? 
Je peux regarder pour m'en occuper si tu veux ! 
Pour l'explorateur, c'est carrément faisable, Publicodes fournit un composant de documentation ! [Exemple d'utilisation dans NGC](https://github.com/datagir/nosgestesclimat-site/blob/081e47687a9293d908a45c9bd28e8fd6605fda11/source/sites/publicodes/pages/Documentation.tsx)

**Comment by Clemog** [comment]
Et pour compléter, j'ai normalement, pour les différente règle intégrer une `note`ou `rééférence` qui donne la source associée

**Comment by Clemog** [comment]
- Trouver un moyen de citer l'étude de NO

**Comment by Clem-mrtn** [comment]
La prio de cette issue est d'abord d'afficher les hypothèses (page catégorie & équivalent) 
Réfléchir dans un deuxième temps comment optimiser l'affichage des sources

**Comment by Clemog** [comment]
- Ajout d'un message simple pour exposer quelques hypothèses supplémentaires sur la page catégorie (pour la page équivalent, ça a moins de sens car la page équivalent permet de faire bouger ces hypothèses)

Prochaines étapes:

- [ ] Consolider les notes et références dans le modèle Publicodes pour mieux expliquer les calculs
- [ ] Exposer la doc d'exploration publicodes dans ImpactCO2 pour les curieux

**Comment by florianpanchout** [comment]
2 issues pour suivre la suite : #200 #201
