### ISSUE TITLE
Uniformisation des données : impact d'un mail page catégorie usage numérique vs. affichage tuile 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#195]
Dans les retours utilisateurs qu'on a pu avoir suite à la diffusion du simulateur, il y en a que je trouvais pertinent autour des différences des données sur le site 
En effet sur la page catégorie usage numérique l'impact carbone d'1 mail est de 0,0001KgCO2e avec les hypothèses paramétrées
![image](https://user-images.githubusercontent.com/76995768/202727180-2222e08b-05a2-471c-b7a2-999bf19d8f2a.png)

Mais lorsque j'utilise le convertisseur, 0,0001Kg équivaut à 0,5 mail 
![image](https://user-images.githubusercontent.com/76995768/202727516-eaa19c61-32d4-4fe2-abe6-4237cf17b032.png)

Evidemment les hypothèses ne sont pas les même mais c'est un peu confusant pour l'utilisateur de ne pas avoir les mêmes valeurs d'une page à l'autre et si différence il y a on devrait être plus explicite  sur les hypothèses qu'on utilise... 
Je pense qu'il y a un travail d'uniformatisation de la données ou des hypothèses à faire sur le site

**Comment by Clemog** [comment]
> Yes, pour moi ça rejoint [cette issue](https://github.com/datagir/impactco2/issues/193) avec le texte explicatif sur la page catégorie.

Yes ! On peut aussi uniformiser non ?

**Comment by Clemog** [comment]
Regarder si pas que les mails (streaming ?)

**Comment by Clemog** [comment]
J'ai travaillé sur l'harmonisation des données : on ne pourra pas atteindre l'égalité par rapport à l'image que tu montres car dans le convertisseur, on a le périmètre complet (avec terminaux) et dans la page usage c'est exclu :/
En revanche, c'est normalement harmonisé entre le convertisseur et les pages "équivalent"
(https://195--impactco2.netlify.app/)

**Comment by Clem-mrtn** [comment]
Oui je comprends ! On a du coup la même chose entre les hypothèses des pages équivalents & le convertisseur 👍 
Je trouverais ça toutefois pas mal **d'afficher les hypothèses** aussi sur le convertisseur pour accompagner la compréhension de l'utilisateur 

Aussi, je me demandais est-ce qu'on arrondirait pas les équivalences affichées dans le convertisseur ? 
Je prend l'exemple de la visio : 


![Image](https://user-images.githubusercontent.com/76995768/204252615-21dfdc59-df92-4846-91c4-a296995af510.png)

On affiche 1H sur la page des équivalents, pourquoi on affiche pas 1h également sur le convertisseur ? 
Ca mériterait de s'harmoniser j'ai l'impression

**Comment by Clem-mrtn** [comment]
Il me semble qu'on s'était dit lors de notre retro la semaine dernière que c'était OK pour cette issue : tu peux merge @florianpanchout ?
