### ISSUE TITLE
Inverser titre et sous titre (page catégorie)

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#197]
Un retour utilisateur : 

La promesse de cette page c'est "Découvrez l'impact sur le climat de certains usages numériques et comparez leurs empreintes carbones.". C'est ça qui devrait être lu en premier et qui permet de comprendre le reste de la page, plutôt que "Empreinte carbone de mes usages numériques"

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/impactco2/commit/bc06b2f833afba65f6bb02cdaf22ac1fbe7aef24
