### ISSUE TITLE
Fix Bug Menu

### ISSUE THREAD

**Issue by Clemog** [datagir/impactco2#202]
https://fix-bug-menu--impactco2.netlify.app/

Je me suis permis de tenter un fix pour un bug au niveau du menu !

- Pour le highlight de "Catégories"
- Pour le highlight de la page catégorie en question dans le menu avec router.asPath plutot que router.pathname
- Un égal" strict pour éviter le highlight de numérique et usagenumérique en même temps

**Comment by florianpanchout** [comment]
C'est merged !

@Clemog J'ai un peu modifié ta proposition. Ça me semblait plus simple comme ça
