### ISSUE TITLE
Harmoniser titres & sous-titres sur les pages catégories 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#203]
#@Suite de l'issue #197 
Afin d'harmoniser toutes les pages du site impactCO2 quelques pistes d'améliorations : 

- [x] Retirer tous les **"."** des sous-titres sur les pages catégories. On en met pas sur la page *usage numérique* et je trouve ça bizarre d'avoir un point à la fin d'un sous-titre 
- [x] **Page Numérique** : **"Comparez l'empreinte carbone des appareils qui le composent, avec leurs usages et leur construction"**
- [x] **Page boisson** : la description ne couvre pas l'ensemble des produits qui sont comparés en dessous, je trouve ça bizarre *(on a aussi du lait, et de l'eau)*. Quitte à être exhaustif je propose **"Comparez l'empreinte carbone de l'eau avec du lait, du soda des boissons alcoolisées, et des boissons chaudes."**
- [x] **Page Fruits & légumes** : je trouve ça personnellement bizarre qu'elle ne soit pas harmonisée avec le reste. Je propose le titre **"Découvrez les fruits & légumes de (mois en select)"** et en sous-titre **"Retrouvez les fruits et légumes de la saison et comparez leurs empreintes carbones"**

**Comment by Clemog** [comment]
Branche de démo : https://203--impactco2.netlify.app/

J'ai repris tes propositions :) J'ai juste mis au singulier : "Retrouvez les fruits et légumes de la saison et comparez leurs empreinte carbone". je crois que les 2 peuvent s'écrire mais je dirais qu'on compare l'empreinte carbone de chacun des F&L (mais c'est du détail ;) )

**Comment by Clem-mrtn** [comment]
C'est bon pour moi ✔️

**Comment by Clemog** [comment]
Fixed by https://github.com/datagir/impactco2/commit/352868f17df8b8d2fce8e2942b1da64d2189c107
