### ISSUE TITLE
Bug : page d'erreur recherche livre de poche 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#209]
Quand je tape depuis la page équivalent liseuse dans la barre de recherche "**livres de poches"** j'ai une page d'erreur :
![image](https://user-images.githubusercontent.com/76995768/207918631-12eaa6b5-5e2a-4574-a4a2-c28959f5c872.png)

Par contre une fois que j'actualiser la page s'affiche

**Comment by Clem-mrtn** [comment]
(toutes recherches d'ailleurs sorry pas que les livres de poches)

**Comment by florianpanchout** [comment]
C'est corrigé !
