### ISSUE TITLE
Bug : affichage de l'emoji Tablette 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#218]
En recettant l'issue #215, j'ai vu que l'**emoji tablette** ne s'affichait pas correctement vs. les autres emojis 

![image](https://user-images.githubusercontent.com/76995768/215052318-cfd9b325-0b0d-4805-a1ee-1147cc47e77e.png)

**Comment by florianpanchout** [comment]
FAKE NEWS!

![Image](https://user-images.githubusercontent.com/8115933/215544016-7066f0da-0679-4d3e-92e8-08dc728968da.png)

Est-ce que tu as le problème en navigation privée ?

**Comment by Clem-mrtn** [comment]
Trop bizarre, je n'ai effectivement plus le problème pourtant j'avais vidé mon cache ! 
Mais du coup non pas le problème en navigation privé non plus :) 
Je ferme cette fake news haha
