### ISSUE TITLE
Laisser la possibilité de rentrer une distance > 10 000 km

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#219]

**Comment by florianpanchout** [comment]
Visible ici : https://deploy-preview-220--impactco2.netlify.app/transport

Ça casse vite l'affichage par contre. Mais vu le peu d'usage de cette fonction, je me demande si ça vaut le coup d'y consacrer plus de temps

**Comment by Clem-mrtn** [comment]
- Pourquoi cette issue ? 
- En terme d'expérience utilisateur je trouve ça pas mal, ça ne casse pas trop l'affichage je trouve 
- Par contre quand je renseigne un chiffre rond : ex 15 000, je me retrouve avec 14997KM pour ne pas faire l'arrondi ?
![Image](https://user-images.githubusercontent.com/76995768/217221335-147b4f42-6f48-4d9c-afd0-c881fe09e92c.png)
![Image](https://user-images.githubusercontent.com/76995768/217221384-6ffbbff5-ff64-4f22-926b-09c4b7ed6b2e.png)

**Comment by florianpanchout** [comment]
C'était suite à [la demande de Maxine ici](https://mattermost.incubateur.net/betagouv/pl/mx4kqp4jyffr7qkxc5xmdbbnay).

Pour le 15000 => 14997 c'est à cause de la fonction logarithmique que j'utilise (pour que les premiers km passent moins vite que les derniers) J'imagine que ça pourrait être mieux mais je suis nul en maths

**Comment by florianpanchout** [comment]
L'app plante lorsque l'on essaie d'entrer 0 via l'input text
