### ISSUE TITLE
Intégrer un support utilisateur (type: Crisp)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#224]
- [ ] Evaluer les différentes solutions de l'outil (parti retours utilisateurs, parti support)
- [ ] Prix / difficulté de mise en place 
- [ ] Identifier le flux (où vont les retours ?)
- [ ] Intégration et parametrage de l'outil sur le site Impact CO2

**Comment by florianpanchout** [comment]
Crisp ne permet pas d'avoir un feedback simple (obligation de passer par un chat avant)

J'ai intégré le module feedback d'Hotjar : https://deploy-preview-253--impactco2.netlify.app/

Les couleurs peuvent être changées via l'option payante (79 € / mois). Option que l'on sera obligé de prendre si l'on souhaite avoir plus de 20 retours par mois

Vous en pensez quoi @Clem-mrtn @Clemog ?

**Comment by Clemog** [comment]
Ça me semble très bien pour tester ! 
Les retours arrivent sur leur plateforme j'imagine ?
C'est peut-être possible mais animer la balise au bout de qques minutes sur le site pourrait être pas mal

**Comment by Clem-mrtn** [comment]
Très bien ! 
Les questions que je me pose : 
- Est-ce qu'avec ce format c'est assez clair que c'est un retour utilisateur et pas juste un feedback ? _(il peut aussi faire des "contributions", ouvrir des sujets etc.)_
- Si on utilise Hotjar est-ce qu'on peut par la même occasion essayer d'autres features d'Hotjar ? 😄 Genre la carte de chaleur par exemple ? 
- > Il est possible de dispatcher ça ailleurs par la suite 
Genre renvoyer les retours sur une autre plateforme genre Airtable ou autres pour le traitement ?

**Comment by florianpanchout** [comment]
> Est-ce qu'avec ce format c'est assez clair que c'est un retour utilisateur et pas juste un feedback ? (il peut aussi faire des "contributions", ouvrir des sujets etc.)

Je ne suis pas sur de comprendre. Les retours utilisateurs plus poussés ne sont pas sensés passer par l'email de contact via [cette issue](https://github.com/datagir/impactco2/issues/78) ?

> Si on utilise Hotjar est-ce qu'on peut par la même occasion essayer d'autres features d'Hotjar ? 😄 Genre la carte de chaleur par exemple ?

On peut utiliser d'autres features d'hotjar mais ça passera automatiquement par une politique cookies différentes de notre actuelle

> Genre renvoyer les retours sur une autre plateforme genre Airtable ou autres pour le traitement ?

J'imagine que c'est possible. Après a t'on besoin de passer par un service tiers en plus ?

**Comment by Clem-mrtn** [comment]
> Je ne suis pas sur de comprendre. Les retours utilisateurs plus poussés ne sont pas sensés passer par l'email de contact via https://github.com/datagir/impactco2/issues/78 ?

C'est une question que je me pose. J'avais le sentiment que le mail de contact Datagir invitait moins au _retour utilisateur_ en grande partie parce que le parcours utilisateur n'était pas optimal : (_faire un retour impact CO2 sur le site de Datagir en répondant à l'adresse de contact._) 
Mais je me demande si ce n'est pas aussi le fait qu'envoyer un mail pour faire un retour utilisateur ce n'est pas optimal comme expérience utilisateur et qu'un form directement sur le site (type support utilisateur) invitait plus facilement à partager ses retours et son expérience.

Après le petit module Hotjar permet les deux ! 


> J'imagine que c'est possible. Après a t'on besoin de passer par un service tiers en plus ?

Non pas spécialement ! Plus simple d'avoir un canal unique 👍

**Comment by Clem-mrtn** [comment]
Comment peut-on aller voir les retours utilisateurs sur Hotjar ? Quel est le compte utilisé ?

**Comment by florianpanchout** [comment]
Je viens de vous inviter via votre email ! (l'ajout de membre est gratuit, ce qui nous évitera de partager un mdp)
