### ISSUE TITLE
Intervertir le placement des logos 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#226]
Afin de mieux valoriser le site sur lequel on est mettre en premier 
1- Logo ICO2
2 - Marianne
3 ADEME

Est-ce que jouer avec les tailles des logos ne pourrait pas être une option également pour valoriser le logo ICO2 tout en laissant les logos RF & ADEME (rassurant) ?

**Comment by florianpanchout** [comment]
Je ne suis pas sur que jouer sur la taille soit une option valide. L'ordre me semble compliqué aussi.

La question est de savoir si l'on souhaite pousser la marque Impact CO2 ou si l'on souhaite rappeler que l'on est un site étatique. J'ai l'impression qu'il serait prématuré d'y répondre avant la fin de l'investigation

**Comment by Clem-mrtn** [comment]
C'est une bonne question en vrai
Je n'ai pas l'impression que ce soit bloquant de valoriser la marque même pendant la période d'investigation
Par contre j'ai un peu regardé sur les différents sites d'autres SE, ou même du DSFR et tout le monde intègre d'abord le logo RF puis leur logo.. 
Par ex :


![Image](https://user-images.githubusercontent.com/76995768/218752780-b1923d86-3780-41e2-928e-b9de4fd6d5f9.png)



![Image](https://user-images.githubusercontent.com/76995768/218752799-249f80ea-d976-4efd-990c-fb19fc422d7a.png)


Par contre j'ai quand même l'impression que leur logo sont plus gros et un peu plus démarqués

**Comment by florianpanchout** [comment]
On peut peut être enlever le ADEME pour commencer ? Ça nous permettrait aussi de modifier notre logo pour qu'il soit plus imposant

**Comment by florianpanchout** [comment]
Logo ADEME enlevé du header, logo Impact CO2 grossi (et proportions changées) et remplacement du logo Datagir par le logo Impact CO2 dans le footer
