### ISSUE TITLE
Logos en dark mode

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#227]
Intégrer les logos RF  + ADEME en transparence afin d'éviter d'avoir les logos avec un fond blanc
![image](https://user-images.githubusercontent.com/76995768/217312315-1a8dfab4-03e6-4559-a234-cb3c69cf3618.png)

**Comment by florianpanchout** [comment]
[La marque de l'état est obligatoirement sur fond blanc](https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/le-bloc-marque)

Mais d'un autre côté, [le site officiel du DSFR ne respecte pas ça](https://www.systeme-de-design.gouv.fr/)...

**Comment by Clem-mrtn** [comment]
J'arrive pas à voir comment passer en dark mode sur le site du DSFR : mais les logos sont passés en transparents ?
Ca peut valoir le coup de poser la question à Xavier qui bosse sur le DSFR ? 🙂

**Comment by florianpanchout** [comment]
Yes 

![Image](https://user-images.githubusercontent.com/8115933/218024478-ba52c0d0-ba81-482c-b23e-5129c39ade5e.png)

À noter que le logo ADEME a un fond blanc intégré dans le rectangle, donc on toucherait encore plus à l'intégrité de la marque si on l'enlevait.

Peut être attendre de répondre à [cette issue](https://github.com/datagir/impactco2/issues/226) avant de réfléchir plus au sujet ?

**Comment by florianpanchout** [comment]
Le logo RF est maintenant sur fond transparent
