### ISSUE TITLE
Modifier les titres des catégories

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#231]
Pour simplifier la lecture des titres et leur compréhension inverser l'ordre : 
Ex : **"Découvrez l'impact du numérique sur le climat"** 

- [x] Mettre à jour les titres pour toutes les catégories  : **"Découvrez l'impact de l'alimentation sur le climat"** 
Habillement, boisson, transport, électroménager _etc_.

**Comment by Clem-mrtn** [comment]
Le titre de la catégorie numérique n'a pas été changé 


![Image](https://user-images.githubusercontent.com/76995768/218687936-55c18727-c0c8-4915-b30b-72cff17c41bf.png)

**Comment by Clem-mrtn** [comment]
J'ai toujours l'ancien titre pour la Catégorie Numérique.
Il faut changer *Découvrez l'impact sur le climat du numérique* par **"Découvrez l'impact du numérique sur le climat"**


![Image](https://user-images.githubusercontent.com/76995768/220160939-9dee8658-8e63-4e1b-bf6d-d3ad13533ef9.png)

**Comment by florianpanchout** [comment]
C'est sur la branche develop : https://develop--impactco2.netlify.app/numerique
