### ISSUE TITLE
Terme équivalent 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#234]
Le terme _équivalent_ est un terme qui peut ne pas être très clair pour l'utilisateur 
c'est un terme que nous avons commencé à utiliser en interne mais qui n'est p-t pas assez vulgarisé ! 

Quelques idées pour le remplacer sur le site mais aussi dans notre vocab.
- Objets 
- éléments 
- Les termes précis de ce quoi on parle : _Habits, modes de transport, appareils électroménager, mobiliers etc._

**Comment by florianpanchout** [comment]
[L'issue précédente sur le sujet](https://github.com/datagir/impactco2/issues/51)

Objets ne fonctionne pas vu que ce ne sont pas toujours des objets

Pas sur qu'éléments soit plus parlant, surtout quand on le compare au mot catégories.

Utiliser les termes précis me semble intéressant mais impossible de l'utiliser partout (affichage tuile par exemple)

**Comment by Clem-mrtn** [comment]
On peut toutefois se poser la question sur le graphique de la catégorie Usages numériques qui mélangent des objets et des gestes de consommation : 


![Image](https://user-images.githubusercontent.com/76995768/218757718-c6aa80f5-cf53-4710-8f4f-c37d137c61eb.png)

**Comment by Clem-mrtn** [comment]
- [ ] Remplacer le terme *equivalent* dans les pages catégories à exception du simulateur _usages numériques_
