### ISSUE TITLE
Le lien "Voir la version détaillée" renvoie vers une 404 sur l'iframe tuiles

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#245]
Visible ici : https://impactco2.fr/integration

Le lien attend une catégorie qui n'est pas renseignée ici (vu que l'on est pas sur une page catégorie)

**Comment by Clemog** [comment]
Pourquoi on ne renvoie pas vers https://impactco2.fr/convertisseur ?

**Comment by florianpanchout** [comment]
Bonne question. C'est modifié (on prend maintenant l'url de l'iframe comme référence)

**Comment by Clem-mrtn** [comment]
Je ne sais pas si il faut que cette issue soit release pour que ça se corrige, mais depuis la branche de pré-prod, sur le configurateur quand on clique sur " _Voir la version détaillée_" on tombe toujours sur une page 404 mais sur la version en prod : 


![Image](https://user-images.githubusercontent.com/76995768/221808357-5868efe1-e1bb-4548-b8df-2fa703064a7e.png)

**Comment by florianpanchout** [comment]
Effectivement, il y a avait une différence entre l'url de l'iframe et celle web. C'est corrigé
