### ISSUE TITLE
Intégrer un lien vers l'enquête utilisateur Impact Livraison

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#257]
Intégrer sur la HP (et qui sera visible également sur les intégrations _iframe_) un lien vers l'enquête utilisateur **Impact Livraison** : https://airtable.com/shrjkhDX06ni42sTd

=> **Lien à retirer mardi 28.02**

**Comment by Clem-mrtn** [comment]
Après discussion avec Laura, on se dit qu'on a aujourd'hui plus de 300 retours sur l'enquête utilisateur, ce qui en fait déjà beaucoup à traiter.
Ca aurait été intéressant de récolter ces retours du site dans le weekend avant de débrancher le questionnaire, mais si on met le lien vers l'enquête aujourd'hui on risque de se retrouver avec beaucoup plus de nouveaux retours à traiter et ça peut risquer de devenir chronophage dans le traitement. Donc pas forcément nécessaire de la partager sur le site

**Comment by florianpanchout** [comment]
Ça marche, c'est retiré
