### ISSUE TITLE
Sources du site : Mise à jour des liens morts

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/impactco2#269]
Avec la fusion des deux bases de données Base Carbone et Base Impact qui ont donné la nouvelle Base Empreinte on a perdu beaucoup de lien vers nos sources (pas de redirection automatique).
Dans une volonté de sourcer toujours les simulateurs et d'être le plus transparent sur les données que l'on utilise pour nos réutilisateurs il faudrait dans un premier temps mettre à jour tous les liens morts des sources pour chaque élément .

J'ai me semble-t-il cartographier l'ensemble des liens morts sur le site et j'ai tenté de recenser les nouveaux liens sur la Base Empreinte : 

**Catégorie chauffage :** 
- Chauffage électrique : https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=Electricite_reglementaire
- chauffage au gaz : https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=gaz
- chuaffage au fioul : https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=New_liquides

**Catégorie transport :** 
- Vélo, marche, voiture élec & thermique, scooter, moto, bus, autocar : https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=Routier2
- TGV, tramway, métro, RER, TER, : https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=Ferroviaire2
- Avion :  https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=aerien

**Catégorie Repas :** 
- Repas végétarien, avec du poulet, avec du boeuf : https://base-empreinte.ademe.fr/documentation/base-carbone?docLink=Repas

**Catégorie boisson :** 
- Vins : https://agribalyse.ademe.fr/app/aliments/5214#Vin_rouge
- lait de soja : https://agribalyse.ademe.fr/app/aliments/18900#Boisson_au_soja,_nature
- lait de vache : https://agribalyse.ademe.fr/app/aliments/19051#Lait_%C3%A9cr%C3%A9m%C3%A9,_pasteuris%C3%A9
- Eau : https://base-empreinte.ademe.fr/documentation/base-impact (j'ai pas miuex...)

Pour aller plus loin dans un deuxième temps et pour répondre aux besoins des réutilisateurs d'avoir des sources précises et claires il faudrait se demander : 

- Pour les aliments on utilise à la fois les FE de la BC mais on source Agribalyse pour le cycle de vie : p-t pas forcément très clair 
- Aujourd'hui pour les catégories numérique, habits, et mobilier on utilise l'étude de Pierre. C'est un PDF à télécharger pas forcément idéal... Si on est amené à mettre à jour les FE numérique avec les données Nega Octet qui seront sur la Base Empreinte c'est à se demander s'il ne vaudrait pas mieux pointer vers tous les éléments de la Base Empreinte

**Comment by florianpanchout** [comment]
Done (en prod)
