### ISSUE TITLE
Fusion MIT & MCCO2 

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#62]
Suite de #60 

Juste une réflexion que je me faisais : pour la catégorie "Déplacements" c'est vraiment Mon Impact Transport... On se retrouve un peu avec un doublon entre les deux simulateurs.
Aussi dans cette version on ne prend toujours pas encore l'impact de la fabrication c'est ça ?

**Comment by florianpanchout** [comment]
C'est vrai que les deux sont proches. 

On pourrait imaginer à terme intégrer MIT à la place de cet écran : https://mcc-v2.netlify.app/categories/deplacement. Il faudra aussi une visualisation particulière pour la catégorie `Usage numérique`. MCC deviendrait un agrégateur de simulateur.

**Comment by Clem-mrtn** [comment]
Je reprends cette issue pour la fusion entre les deux simulateurs MCCO2 & MIT 
Liste de tâches : 
- [ ] Questions : conserver l'URL MIT ? Redirection automatique ? Coexistence des deux URL ? Simplement même affichage d'un site à l'autre ? 
- [ ] Atelier du 26/07

**Comment by Clem-mrtn** [comment]
- [ ] Redirection de l'url monimpacttransport.fr vers https://monconvertisseurco2.fr/categories/transport 
- [ ] Changer le wording : Déplacement par Transport sur MCCO2 
- [ ] Conserve l'UX/UI de MIT avec les couleurs de MCCO2 
- [ ] Intégration du contenu écrit de MIT également sur MCCO2 (=> ++ pour le SEO)
- [ ] Possibilité d'intégrer en iframe MIT depuis MCCO2 
- [ ] Incorporer l'API 

Les utilisateurs de _l'iframe_ auront automatiquement le nouvel affichage. 
Et au clic, dans leur simulation : un nouvel onglet s'ouvrira sur MCCO2. 

**Estimation du travail : 8 jours environ**

**Comment by florianpanchout** [comment]
Question que je me pose : quelle charte graphique on reprends pour cette fusion ? MIT ou MCC ? Ça ne concerne que les couleurs et ça prends 30 secondes à changer.

@Clem-mrtn @martinregner

**Comment by Clem-mrtn** [comment]
On s'était dit avant les vacances qu'on gardait l'UX/UI de MIT mais qu'on mettait au couleur de MCCO2 (vert) pour l'instant 
Donc je resterai là dessus moi, d'autant que de basculer du vert au rouge de MIT directement sur le site c'est un p-t peu violent 😅

**Comment by florianpanchout** [comment]
Ici il s'agirait de changer la couleur pour l'ensemble du site MCC, pas juste pour la partie transport

**Comment by Clem-mrtn** [comment]
Je préfère le vert au rouge 
Pour un simulateur simple rouge c'était pas dérangeant mais pour tout un site entier, je trouve le vert + agréable mais c'est un choix subjectif

**Comment by florianpanchout** [comment]
Je réouvre tant que la fusion n'est pas effective

**Comment by florianpanchout** [comment]
Done

**Comment by florianpanchout** [comment]
Il reste la question de cette page : https://datagir.ademe.fr/apps/mon-impact-transport/

- Est-ce qu'elle disparait totalement ? (avec redirection vers https://datagir.ademe.fr/apps/impact-co2/)
- Est-ce qu'elle est renommée Impact CO2 Transport ?

@martinregner

**Comment by martinregner** [comment]
Dans un premier temps, avant refonte totale du site, on garde l'ancienne entrée de Mon Impact Transport apps/mon-impact-transport pour introduire le changement de nom (accompagné du gif si ça rentre) et garder une continuité sur ce produit.
Ce n'est pas rare les sites qui redirigent sur la page [apps/mon-impact-transport/](https://datagir.ademe.fr/apps/mon-impact-transport/) à la place de [monimpacttransport.fr](https://monimpacttransport.fr/).
Je propose : 
> **Mon Impact Transport rejoint Impact CO2**
En plus des fonctionnalités que vous connaissiez sur le transport, découvrez d'autres catégories et l'impact d'autres gestes & objets du quotidien

**Comment by florianpanchout** [comment]
Done
