### ISSUE TITLE
Modifier partie "Comment intégrer ces données à mon site ou application ?"

### ISSUE THREAD

**Issue by florianpanchout** [datagir/impactco2#78]
Rendre plus visible l'accès au configurateur et moins visible l'email de contact

**Comment by florianpanchout** [comment]
Finalement rendre plus visible les deux

**Comment by Clem-mrtn** [comment]
Il y a un sujet FAQ que @maxinesabater a initié qui pourrait être intéressant de croiser avec la valorisation de cette rubrique : https://pad.incubateur.net/m3B9wYpsSomd6JG6EPDYNw

**Comment by florianpanchout** [comment]
[Une proposition de nouveau layout](https://deploy-preview-255--impactco2.netlify.app/) pour le footer, qui englobe la mise en valeur et de la partie intégration et l'affichage du mail dans le footer

(on retire aussi les textes SEO qui étaient apparus par erreur dans les iframes)

@Clem-mrtn @Clemog vous en pensez quoi ?

**Comment by florianpanchout** [comment]
> Il y a un sujet FAQ que @maxinesabater a initié qui pourrait être intéressant de croiser avec la valorisation de cette rubrique : https://pad.incubateur.net/m3B9wYpsSomd6JG6EPDYNw

Tu voudrais créer une page FAQ avec ce contenu ?

Il y a quelques rubriques qui ne sont pas forcement à leur place sur ICO2 non ? "Est-il possible de recevoir et stocker les données de simulations effectuées ?" ou "Face à la hausse du prix de l’énergie, à quelle aide exceptionnelle de l’État puis-je prétendre ?" par exemple

**Comment by maxinesabater** [comment]
> > Il y a un sujet FAQ que @maxinesabater a initié qui pourrait être intéressant de croiser avec la valorisation de cette rubrique : https://pad.incubateur.net/m3B9wYpsSomd6JG6EPDYNw
> 
> Tu voudrais créer une page FAQ avec ce contenu ?
> 
> Il y a quelques rubriques qui ne sont pas forcement à leur place sur ICO2 non ? "Est-il possible de recevoir et stocker les données de simulations effectuées ?" ou "Face à la hausse du prix de l’énergie, à quelle aide exceptionnelle de l’État puis-je prétendre ?" par exemple

L'idée était de recenser les questions les plus courantes sur les différents canaux de contact ! Effectivement, celles qui ne relèvent pas de notre domaine (DPE, chèque énergie, aide à la rénovation énergétique, etc.) sont très fréquentes. 

Avec @Clem-mrtn on a pensé à plusieurs pistes pour éviter ces prises de contact ou gagner du temps dans la réponse, comme un message d'alerte indiquant que Datagir n'a pas vocation à prendre en charge ce type de demandes, le renvoi vers les sites gouvernementaux de référence ou encore un formulaire de contact plus "costaud". 

Je propose qu'on fasse le tour de cette FAQ au prochain sprint planning pour décider ce qu'on en fait ! 👍

**Comment by florianpanchout** [comment]
Mais on parle du formulaire du site Datagir ou des 3 emails que l'on reçoit via ICO2 ?

**Comment by maxinesabater** [comment]
> Mais on parle du formulaire du site Datagir ou des 3 emails que l'on reçoit via ICO2 ?

Ici du formulaire et du mail Datagir, dans l'optique d'intégrer une page de FAQ sur ICO2.

**Comment by florianpanchout** [comment]
Donc parce que l'on a des mails sur le DPE via un formulaire de contact sur un site qui est amené à fortement évoluer prochainement (voir disparaitre), on écrit une FAQ sur un autre site ?

**Comment by maxinesabater** [comment]
> Donc parce que l'on a des mails sur le DPE via un formulaire de contact sur un site qui est amené à fortement évoluer prochainement (voir disparaitre), on écrit une FAQ sur un autre site ?

Une FAQ sur ICO2, dédiée à ICO2 et à son utilisation, qui ne prenne pas en compte toutes les questions relatives aux sujets pour lesquels nous n'avons aucune habilitation (DPE & co), je pense que c'est pertinent oui ! :)

**Comment by maxinesabater** [comment]
Ce pad est vraiment juste un brain dump pour recenser toutes les questions auxquelles je réponds régulièrement, elle est à revoir, trier et alléger ;)

**Comment by Clem-mrtn** [comment]
> [Une proposition de nouveau layout](https://deploy-preview-255--impactco2.netlify.app/) pour le footer, qui englobe la mise en valeur et de la partie intégration et l'affichage du mail dans le footer

Je trouve ça très chouette comme ça ! 
Pétouille mais j'aérerais juste le petit texte en dessous avec un saut de ligne : 

" Intégrez facilement nos simulateurs grâce (**il manque un accent ^**) à [notre configurateur](https://deploy-preview-255--impactco2.netlify.app/integration). 

Que vous souhaitiez [convertir (je remplacerais plutôt que visualiser) un poids en CO2e](https://deploy-preview-255--impactco2.netlify.app/integration?type=tuiles), [comparer différents modes de transport](https://deploy-preview-255--impactco2.netlify.app/integration?type=transport), ou encore découvrir [l'impact de vos usages numériques](https://deploy-preview-255--impactco2.netlify.app/integration?type=usagenumerique), il y a un simulateur pour vous !

CTA **Voir le configurateur** "

**Comment by Clem-mrtn** [comment]
Pour la FAQ ça rejoint la discussion qu'on avait au séminaire que ça pouvait être intéressant d'en intégrer une sur Impact CO2, pour répondre **aux questions liées à ICO2** 

Une fois le contenu validé ça pourrait être intéressant de s'inspirer de ce qui a été fait sur NGC, je crois qu'ils ont retravaillé le sujet : 
<img width="1161" alt="Capture d’écran 2023-02-22 à 10 28 29" src="https://user-images.githubusercontent.com/76995768/220578906-a806fa63-1c3d-4114-a2a0-4651a2a80e00.png">

<img width="1195" alt="Capture d’écran 2023-02-22 à 10 36 18" src="https://user-images.githubusercontent.com/76995768/220580733-9ee63612-44cf-4e23-a9a3-6bdbddc822c6.png">

**Comment by Clem-mrtn** [comment]
Pour le footer *Qui sommes-nous* avec le mail de contact, ça lie à l'issue #254 , 
Tu l'as déjà modifié, mais je pense qu'on peut retravaillé la promesse, je vais regarder pour un petit texte 

Je m'interroge aussi sur ce mail datagir@ademe.fr... bon ce n'est qu'un mail mais on ne fait plus du tout mention de Datagir nul part sur le site, est-ce que c'est "clair" pour l'utilisateur qu'en nous contactant par ce canal il aura ses réponses à Impact CO2  ?

**Comment by florianpanchout** [comment]
Pour le Qui sommes-nous (et l'email Datagir) je me suis dit qu'il valait mieux attendre d'en savoir plus sur l'avenir de la marque Datagir
